### ISSUE TITLE
Не  могу установить  модуль 

### ISSUE THREAD

**Issue by Fedor858** [developeruz/easyii-user-module#1]
Problem 1                                                                                  
   - Can only install one of: noumo/easyii[dev-master, dev-dev].                            
   - Can only install one of: noumo/easyii[dev-master, dev-dev].                            
   - Can only install one of: noumo/easyii[dev-master, dev-dev].                            
   - developeruz/easyii-user-module dev-master requires noumo/easyii dev-master -> satisfiab
ii[dev-master].                                                                             
   - Installation request for developeruz/easyii-user-module * -> satisfiable by developeruz
ule[dev-master].                                                                            
   - Installation request for noumo/easyii dev-dev -> satisfiable by noumo/easyii[dev-dev].

**Comment by developeruz** [comment]
У вас уже установлена версия noumo/easyii dev-dev, а у меня в зависимостях прописана версия dev-master.
Если вам принципиально чтобы тянуло из dev-dev - напишите пожалуйста почему, может мне тоже стоит переключится на нее.
Если вы не знаете почему у вас dev-dev то найдите в comoser.json строчки
```php
 "require": {
        "php": ">=5.4.0",
        "noumo/easyii": "dev-dev",
```
замените на 
```php
 "require": {
        "php": ">=5.4.0",
        "noumo/easyii": "dev-master",
```
запустить `composer install` и продолжайте установку User модуля.

**Comment by Fedor858** [comment]
У меня  версия  отсюда http://easyiicms.com/uploads/files/new.zip,
http://www.yiiframework.ru/forum/viewtopic.php?f=9&t=22079&start=280,тут  можно  прочитать  о ней
если  вы сидите  на  старой мастер  ветке  то  переходить  обязательно,
Спасибо.

**Comment by developeruz** [comment]
Ок, спасибо. Попробуй установить dev-dev версию и посмотрю что нужно поменять. Вариант установки из архива мне не нравится и он не годится в качестве зависимости для чужих пакетов.

**Comment by developeruz** [comment]
Оказывается ничего менять не нужно. Убрала зависимость от noumo/easyii вообще, т.к врятли кто станет ставить этот модуль без самой CMS.
