### ISSUE TITLE
Проблемы с  конфигурацией

### ISSUE THREAD

**Issue by Fedor858** [developeruz/easyii-user-module#2]
Модуль  установил) теперь  при  попытке создать пользователя в  консоли  вылетает  вот  это 
Exception 'yii\base\UnknownPropertyException' with message 'Setting unknown property: yii\console\Application::user'
in C:\OpenServer\domains\test\vendor\yiisoft\yii2\base\Component.php:201
Stack trace:
#0 C:\OpenServer\domains\test\vendor\yiisoft\yii2\BaseYii.php(525): yii\base\Component->__set('user', Array)
#1 C:\OpenServer\domains\test\vendor\yiisoft\yii2\base\Object.php(105): yii\BaseYii::configure(Object(yii\console\Application), Array)
#2 C:\OpenServer\domains\test\vendor\yiisoft\yii2\base\Application.php(204): yii\base\Object->__construct(Array)
#3 C:\OpenServer\domains\test\vendor\yiisoft\yii2\console\Application.php(89): yii\base\Application->__construct(Array)
#4 C:\OpenServer\domains\test\yii(22): yii\console\Application->__construct(Array)
#5 {main}
Если я  прописываю в  params.php   -  'admins' => ['admin']  то   -
Parse error: syntax error, unexpected '=>' (T_DOUBLE_ARROW) in C:\OpenServer\domains\test\app\config\params.php on line 2

**Comment by developeruz** [comment]
У вас прописан компонент `user` в console.php, у меня такого в инструкции нет. 
Скиньте ваш конфиг console.php и web.php 

Весь файл `params.php` должен выглядеть примерно так, если вы его никогда раньше не меняли:
```php
<?php

return [
    'admins' => ['admin']
];
```
у вас явно синтаксическая ошибка.

**Comment by Fedor858** [comment]
user в  console был  потому что я  его  туда  прописал,на  данный момент console чист
<?php
$params = require(__DIR__ . '/params.php');
$db = require(__DIR__ . '/db.php');

$basePath =  dirname(__DIR__);
$webroot = dirname($basePath);

return [
    'id' => 'app-console',
    'basePath' => $basePath,
    'runtimePath' => $webroot . '/runtime',
    'vendorPath' => $webroot . '/vendor',
    'bootstrap' => ['log', 'gii'],
    'controllerNamespace' => 'app\commands',
    'modules' => [
        'gii' => 'yii\gii\Module',
    ],
    'components' => [
        'cache' => [
            'class' => 'yii\caching\FileCache',
        ],
        'log' => [
            'targets' => [
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['error', 'warning'],
                ],
            ],
        ],
        'db' => $db,
    ],
    'params' => $params,
];

**Comment by Fedor858** [comment]
но  юзер  там  создаваться  не  хочет -
 Unknown command: user/create
 То есть  если  в  console.php  прописать 
 'user' => [
                'class' => 'dektrium\user\Module',
            ],
 то  получим  Exception 'yii\base\UnknownPropertyException' with message 'Setting unknown property: yii\console\Application::user' 
если  не прописывать  то 
> yii  user/create
Unknown command: user/create

**Comment by developeruz** [comment]
Вы его скорее всего не туда прописываете
Найдите кусок в config/console.php
 ```php
  'modules' => [
        'gii' => 'yii\gii\Module'
    ],
```
и замените на 
```php
'modules' => [
        'gii' => 'yii\gii\Module',
        'user' => [
            'class' => 'dektrium\user\Module',
        ],
    ],
```

**Comment by developeruz** [comment]
Все вопросы по консоли и настройкам `dektrium/yii2-user` лучше всего адресовать сюда: https://github.com/dektrium/yii2-user
Данный модуль только помогает интегрировать этот пакет в EasyiiCMS. Т.е сюда любые вопросы по интеграции, но не по EasyiiCMS или `dektrium/yii2-user`
